---
- name: Install docker + compose plugin
  apt:
    name:
      - docker.io
      - docker-compose-plugin
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure docker service running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create working dir
  file:
    path: /opt/axialy
    state: directory

- name: Copy docker-compose stack
  copy:
    src: "{{ playbook_dir }}/../../docker/compose.yml"
    dest: /opt/axialy/docker-compose.yml
    mode: 0644

- name: Create env-file with secrets
  copy:
    dest: /opt/axialy/.env
    mode: '0600'
    content: |
      DB_HOST={{ lookup('vars', 'db_host') | default('') }}
      DB_PORT={{ lookup('vars', 'db_port') | default('3306') }}
      ADMIN_DEFAULT_USER={{ lookup('env', 'ADMIN_DEFAULT_USER') }}
      ADMIN_DEFAULT_PASSWORD={{ lookup('env', 'ADMIN_DEFAULT_PASSWORD') }}
      ADMIN_DEFAULT_EMAIL={{ lookup('env', 'ADMIN_DEFAULT_EMAIL') }}

- name: Pull & start services
  community.docker.docker_compose_v2:
    project_src: /opt/axialy
