#cloud-config
###############################################################################
#  This template is rendered by Terraform.  Variables come from the DB
#  resources that Terraform just created (see main.tf).  Everything is written
#  to /etc/axialy_admin_env, which bootstrap_env.php consumes on first page-load.
###############################################################################

write_files:
  - path: /etc/axialy_admin_env
    permissions: "0600"
    owner: root:root
    content: |
      # Axialy-Admin DB credentials — *generated by Terraform*
      DB_HOST=${db_host}
      DB_PORT=${db_port}
      DB_NAME=${db_name}
      DB_USER=${db_user}
      DB_PASSWORD=${db_pass}

# minimal packages + nginx splash-page removal (same as other droplets)
package_update: true
packages:
  - nginx

runcmd:
  - systemctl enable --now nginx
  - ufw allow 'Nginx Full' || true
  - rm -f /var/www/html/index.nginx-debian.html || true
