version: "3.9"

services:
  php:
    image: ${PHP_IMAGE:-ghcr.io/axiamax/axialy-admin-php:latest}
    restart: unless-stopped
    environment:
      APP_ENV: "production"
    volumes:
      # env-file where AdminDBConfig expects it
      - /opt/axialy/.env:/home/i17z4s936h3j/private_axialy/.env.admin:ro
    networks: [ web ]

  nginx:
    build: ./nginx
    restart: unless-stopped
    depends_on: [ php ]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks: [ web ]

networks:
  web:
    driver: bridge
