services:
  php:
    image: ${PHP_IMAGE:-ghcr.io/axiamax/axialy-admin-php:latest}
    restart: unless-stopped
    environment:
      APP_ENV: "production"
    volumes:
      - /opt/axialy/.env:/home/i17z4s936h3j/private_axialy/.env.admin:ro
    networks: [ web ]
