---
- hosts: all
  become: yes

  vars:
    # ── Values injected from the GitHub workflow ─────────────────────────────
    php_image:      "{{ lookup('env','PHP_IMAGE') }}"
    admin_user:     "{{ lookup('env','ADMIN_DEFAULT_USER') }}"
    admin_pass:     "{{ lookup('env','ADMIN_DEFAULT_PASSWORD') }}"
    admin_email:    "{{ lookup('env','ADMIN_DEFAULT_EMAIL') }}"
    db_host:        "{{ lookup('env','DB_HOST') }}"
    db_port:        "{{ lookup('env','DB_PORT') }}"
    db_username:    "{{ lookup('env','DB_USERNAME') }}"
    db_password:    "{{ lookup('env','DB_PASSWORD') }}"

    # ── Paths on the droplet ─────────────────────────────────────────────────
    deploy_root: "/opt/axialy"
    compose_dir: "/opt/axialy/docker"
    env_path:    "/opt/axialy/.env"

  tasks:
    # 1️⃣  Install Docker Engine + Compose plugin
    - name: Install Docker Engine and Compose plugin
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com | sh
        apt-get -qq update
        apt-get -qq install -y docker-compose-plugin
        usermod -aG docker ${SUDO_USER:-root} || true
      args:
        warn: false

    # 2️⃣  Ensure base directories
    - name: Ensure directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ deploy_root }}"
        - "{{ compose_dir }}"

    # 3️⃣  Write the application .env file
    - name: Write application .env file
      ansible.builtin.copy:
        dest: "{{ env_path }}"
        mode: '0600'
        content: |
          # Auto-generated by Ansible – {{ ansible_date_time.iso8601 }}

          # ── Admin DB ───────────────────────────────
          DB_HOST={{ db_host }}
          DB_PORT={{ db_port }}
          DB_NAME=Axialy_ADMIN
          DB_USER={{ db_username }}
          DB_PASSWORD={{ db_password }}

          # ── UI DB ─────────────────────────────────
          UI_DB_HOST={{ db_host }}
          UI_DB_PORT={{ db_port }}
          UI_DB_NAME=Axialy_UI
          UI_DB_USER={{ db_username }}
          UI_DB_PASSWORD={{ db_password }}

          # ── Admin bootstrap account ───────────────
          ADMIN_DEFAULT_USER={{ admin_user }}
          ADMIN_DEFAULT_PASSWORD={{ admin_pass }}
          ADMIN_DEFAULT_EMAIL={{ admin_email }}

    # 4️⃣  Copy Docker bundle
    - name: Copy docker directory
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../docker/"
        dest: "{{ compose_dir }}/"
        mode: preserve

    # 5️⃣  Copy application source
    - name: Copy Axialy Admin product source
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../axialy-admin-product/"
        dest: "{{ deploy_root }}/axialy-admin-product/"
        mode: preserve

    # 6️⃣  Launch / update the stack
    - name: Start the stack
      community.docker.docker_compose_v2:
        project_name: axialy-admin
        project_src: "{{ compose_dir }}"
        build: false
        state: present
