name: CI

on:
  pull_request:
  workflow_dispatch:        # manual run from the “Actions” tab
    inputs:
      run_infra:
        description: 'Run CI manually only - never on push'
        required: false
        default: 'true'

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PHP lint
        run: |
          # lint every PHP file in the product folder
          find axialy-admin-product -type f -name '*.php' -print0 \
            | xargs -0 -n1 -P4 php -l
