name: Deploy Marketing Site
on:
  push:
    branches: [ "main" ]
    paths: [ "axialy-marketing-site/**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_TOKEN:     ${{ secrets.DIGITALOCEAN_TOKEN }}
      DROPLET_SSH_KEY:        ${{ secrets.DROPLET_SSH_KEY }}
      DROPLET_SSH_PASSPHRASE: ${{ secrets.DROPLET_SSH_PASSPHRASE }}

    steps:
    - uses: actions/checkout@v4

    - name: Install & auth doctl
      run: |
        set -e
        ver=$(curl -s https://api.github.com/repos/digitalocean/doctl/releases/latest |
              grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        curl -sL "https://github.com/digitalocean/doctl/releases/download/v${ver}/doctl-${ver}-linux-amd64.tar.gz" |
          tar -xz
        sudo mv doctl /usr/local/bin
        doctl auth init -t "$DIGITALOCEAN_TOKEN"

    - id: ip
      name: Look up marketing droplet IP
      run: |
        ip=$(doctl compute droplet list --format Name,PublicIPv4 --no-header \
               | awk '$1=="axialy.ai"{print $2; exit}')
        [ -n "$ip" ] || { echo "::error::axialy.ai droplet not found"; exit 1; }
        echo "ip=$ip" >> "$GITHUB_OUTPUT"

    - name: Wait for SSH
      run: |
        for i in {1..30}; do
          nc -z -w3 ${{ steps.ip.outputs.ip }} 22 && exit 0
          sleep 5
        done
        echo "::error::SSH never became ready"; exit 1

    - name: Ensure NGINX is installed & listening
      uses: appleboy/ssh-action@v0.1.6
      with:
        host:       ${{ steps.ip.outputs.ip }}
        username:   root
        key:        ${{ env.DROPLET_SSH_KEY }}
        passphrase: ${{ env.DROPLET_SSH_PASSPHRASE }}
        script: |
          set -euo pipefail
          if ! command -v nginx >/dev/null 2>&1; then
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            apt-get install -y nginx
          fi
          systemctl enable --now nginx
          ufw allow 'Nginx Full' || true
          ss -ltnp | grep -E ':80' || { echo "::error::port 80 not open"; exit 1; }

    - name: Rsync new build
      uses: appleboy/scp-action@v0.1.5
      with:
        host:       ${{ steps.ip.outputs.ip }}
        username:   root
        key:        ${{ env.DROPLET_SSH_KEY }}
        passphrase: ${{ env.DROPLET_SSH_PASSPHRASE }}
        source:     axialy-marketing-site/*
        target:     /var/www/html/
        strip_components: 1
        timeout:    120s
