name: Provision Admin Infra

on:
  push:
    branches: [ "main" ]
    paths:
      - "infra/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_TOKEN:     ${{ secrets.DIGITALOCEAN_TOKEN }}
      TF_VAR_do_token:        ${{ secrets.DIGITALOCEAN_TOKEN }}
      TF_VAR_ssh_fingerprint: ${{ secrets.SSH_FINGERPRINT }}

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.2

    - name: Terraform init / plan / apply
      working-directory: infra
      run: |
        terraform init -input=false
        terraform apply -auto-approve -input=false
